### ISSUE TITLE
サイトトップイラスト出来る人探し

### ISSUE THREAD

**Issue by kamiyam** [jsgirls-osaka/docs#1]
トップ絵を描ける人探し

**Comment by kamiyam** [comment]
依頼してるマン

**Comment by konitter** [comment]
:+1:
@shimael にもトップ絵のこと言ったら「いけるかも」ってことやったんで、もしそちらのが難しそうならshimaelに。

**Comment by kamiyam** [comment]
#2 で挙がっていたトップ絵の件、発注済みです。
6/14上がり予定ですが、東京分で仮組みしましょうか。。。

**Comment by konitter** [comment]
了解です。どもですー。
