### ISSUE TITLE
Vol.1 イベントページ作成にあたって

### ISSUE THREAD

**Issue by konitter** [jsgirls-osaka/docs#2]
もうあまり時間もないので、そろそろ募集を開始したいと思ってます。
で、イベントページの準備にあたり諸々確認です。

お忙しいところ申し訳ないのですが、ご協力ください。

（福岡のやつを参考に）
http://jsgirls.org/events/fukuoka-201406.html
## 開催場所

他に良さげな候補がなければTAMさんで良いですか？
## トップ絵

@kamiyam ﻿さん、 #1 のその後どんな感じでしょう？
時間かかりそうなら取りあえず東京のやつ↓入れときますかね。
http://jsgirls.org/events/tokyo-201403.html
## メンター、チューター欄

みなさま、下記について急ぎ返答ください。
- 表示する名前
- 社名（出したい場合のみで）
- Twitter、FacebookなどリンクしたいSNSおよびそのアドレス（ブログや個人サイトへのリンクでも可）
- アイコン（基本的には上記SNSから引っ張りますが別のものがよければそのURL）

※メンター、チューターはあと2・3人は欲しいです。周りによさそうな人がいれば積極的に声かけをお願いします。メンターでなくとも受付など雑務をやってくれる方も欲しいです。
## 協賛・協力

今のところ協賛の会社はないと思うんですが…、会場提供的な意味でTAMさん出しちゃっていいんですかね？？
協力のところは、サイバーさん入れていいのかな？？

**Comment by kamiyam** [comment]
開催場所 TAMさんで行きましょい。

**Comment by konitter** [comment]
@kamiyam 了解ですー。

@matsuoshi キープしてもらってた御社のコワーキングスペースの件ですが、7/5確定でお願いします。時間は12:00～19:00とかでいけますか？

**Comment by matsuoshi** [comment]
了解です、おそらく問題ないと思いますが、時間を含めて確認しますね

**Comment by matsuoshi** [comment]
7/5土 12:00〜19:00
確定でOKですー

また、協賛にTAMの名前はナシでOKです、

> 会場: [TAM Coworking](https://www.facebook.com/TAMCoworking)

と、リンクをしていただければー

**Comment by konitter** [comment]
@matsuoshi 了解ですー。確認ありがとうございました！

**Comment by konitter** [comment]
イベントページを作ってみました。こんな感じでどうでしょうか？？
ここをこうしたほうがいいとかあったら言ってください。

![cap](https://cloud.githubusercontent.com/assets/1539320/3278446/1b76690c-f3c0-11e3-814e-3cc1f3b0c706.png)
