### ISSUE TITLE
協賛・協力の定義について確認

### ISSUE THREAD

**Issue by kamiyam** [jsgirls-osaka/docs#3]
#2 協賛と協力について @t32k に確認した方が良い?

協力という意味では各会社･個人動いてもらっているし。

**Comment by konitter** [comment]
@kamiyam そうすね。一応確認お願いしますー。

**Comment by t32k** [comment]
@kamiyam 
- 協賛：金銭的なものをともなう協力（食事代、施設貸、等）
- 協力：善意の協力

って感じですが、とくにスポンサーさんの意向がないかぎり全部まとめて『協力』で良いかと思いますが、ケースバイケースで。

**Comment by kamiyam** [comment]
:+1:
