### ISSUE TITLE
メンター･チューター内容入力

### ISSUE THREAD

**Issue by kamiyam** [jsgirls-osaka/docs#4]
#2 各人プロフィール登録よろ

メンター･チューターとして記載します
http://jsgirls.org/events/fukuoka-201406.html

**Comment by kamiyam** [comment]
名前: かみやん
社名: Meteorworks
Twitter: https://twitter.com/kamiyam
Facebook: https://www.facebook.com/rh.kamiyam?ref=hl
アイコン: https://avatars1.githubusercontent.com/u/171659

**Comment by konitter** [comment]
名前: 小西 春輝
Facebook: https://www.facebook.com/konitter
アイコン: https://avatars1.githubusercontent.com/u/1539320

**Comment by shimael** [comment]
名前: しまえる
Twitter: https://twitter.com/shimael
アイコン: https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xfa1/t1.0-1/c12.12.155.155/523943_336176199776417_672702104_n.jpg
（urlこれでいけてるかいのぉ）

**Comment by matsuoshi** [comment]
名前: マツオ
fb: https://www.facebook.com/matsuoshi
tw: https://twitter.com/matsuoshi
icon: https://avatars0.githubusercontent.com/u/73213?s=160

**Comment by 3panda** [comment]
名前: 3panda
fb: https://www.facebook.com/3panda
tw: https://twitter.com/3panda
icon: https://avatars1.githubusercontent.com/u/463866?s=160

**Comment by w3gjp** [comment]
名前: 上田 遼
fb: https://www.facebook.com/ryoueda
tw: https://twitter.com/w3gjp
icon: https://avatars2.githubusercontent.com/u/615191

**Comment by yokotak0527** [comment]
名前: yokotak0527
fb: https://www.facebook.com/YokotaKenji
tw: https://twitter.com/yokotak0527
icon: https://avatars3.githubusercontent.com/u/454935

**Comment by nobu222** [comment]
名前:二神 暢彦
fb:https://www.facebook.com/nobuhiko.futagami
tw:https://twitter.com/bobu_web
icon:https://avatars1.githubusercontent.com/u/6554937?u=a886eb7f05120a824c979409c96e43a8fd4a66e9&s=140

**Comment by MATSUDAEmi** [comment]
名前：松田
fb:https://www.facebook.com/emi.matsuda.3785
icon:https://scontent-a.xx.fbcdn.net/hphotos-prn2/t1.0-9/945412_536894723053027_1838075977_n.jpg

**Comment by tanakahisateru** [comment]
名前: 田中ひさてる
社名: (株)ことば研究所
Twitter: https://twitter.com/tanakahisateru
Facebook: https://www.facebook.com/tanakahisateru
アイコン: https://avatars1.githubusercontent.com/u/403893

**Comment by kamiyam** [comment]
次回まで 一旦クローズ
